apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.api.containerPort }}
          env:
            - name: APP_MODE
              value: {{ .Values.api.mode | quote }}
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: {{ .Values.secrets.existingSecretName }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.api.containerPort }}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.api.containerPort }}
            initialDelaySeconds: 10
            periodSeconds: 20
