apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: {{ .Values.namespace }}
data:
  RUST_LOG: {{ .Values.config.RUST_LOG | quote }}
  RABBITMQ_URL: {{ .Values.config.RABBITMQ_URL | quote }}
  S3_ENDPOINT: {{ .Values.config.S3_ENDPOINT | quote }}
  S3_BUCKET: {{ .Values.config.S3_BUCKET | quote }}
  NEXUS_URL: {{ .Values.config.NEXUS_URL | quote }}
