apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backend-secrets
  namespace: service-processes
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-store
    kind: ClusterSecretStore
  target:
    name: backend-secrets
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: service-processes/prod
        property: DATABASE_URL
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: service-processes/prod
        property: AWS_ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: service-processes/prod
        property: AWS_SECRET_ACCESS_KEY
